# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boxcoxar <- function(yobs, miss, a, xobs, zobs, uobs, mu_beta0, Sig_beta0, mu_alpha0, Sig_alpha0, mu_eta0, Sig_eta0, ndiscard, nskip, nkeep, verbose) {
    .Call(`_TSEnergy_boxcoxar`, yobs, miss, a, xobs, zobs, uobs, mu_beta0, Sig_beta0, mu_alpha0, Sig_alpha0, mu_eta0, Sig_eta0, ndiscard, nskip, nkeep, verbose)
}

boxcoxar_amh <- function(yobs, miss, a, xobs, zobs, uobs, mu_beta0, Sig_beta0, mu_alpha0, Sig_alpha0, mu_eta0, Sig_eta0, ndiscard, nskip, nkeep, verbose) {
    .Call(`_TSEnergy_boxcoxar_amh`, yobs, miss, a, xobs, zobs, uobs, mu_beta0, Sig_beta0, mu_alpha0, Sig_alpha0, mu_eta0, Sig_eta0, ndiscard, nskip, nkeep, verbose)
}

