# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boxcoxar_amh <- function(yobs, miss, a, xobs, zobs, uobs, mu_beta0, Sig_beta0, mu_alpha0, Sig_alpha0, mu_eta0, Sig_eta0, ndiscard, nskip, nkeep, boxcox_flag, verbose) {
    .Call(`_TSEnergy_boxcoxar_amh`, yobs, miss, a, xobs, zobs, uobs, mu_beta0, Sig_beta0, mu_alpha0, Sig_alpha0, mu_eta0, Sig_eta0, ndiscard, nskip, nkeep, boxcox_flag, verbose)
}

calc_modelfit_residuals <- function(yobs, xobs, zobs, uobs, beta, alpha, eta, sig2, rho, lam, nkeep, verbose) {
    .Call(`_TSEnergy_calc_modelfit_residuals`, yobs, xobs, zobs, uobs, beta, alpha, eta, sig2, rho, lam, nkeep, verbose)
}

singleMonitor <- function(y_surveill, yh_bar, sigma, nyears, sig_level, c, B1, B2, B3, verbose) {
    .Call(`_TSEnergy_singleMonitor`, y_surveill, yh_bar, sigma, nyears, sig_level, c, B1, B2, B3, verbose)
}

